### ISSUE TITLE
Is it possible to contribute to the HTTPS list?

### ISSUE THREAD

**Issue by PrSunflower** [duckduckgo/smarter-encryption#7]
Hi everyone 👋, I am using Firefox and I really like this extension, thanks a lot to everyone who participated in its development 😊

I stumbled upon a website : http://alliance-francaise-maurice.com/ which has an encrypted version: https://alliance-francaise-maurice.com/

but DDG Smarter Encryption didn't automatically make me switch to the HTTPS version.

I know dozens of websites like these and I would like to know if there was a way I can contribute to the "large list of websites", say propose a website that I've found and the developers examine if my request is valid or not to add this website to DDG's list.

I would be grateful if you can answer me 🙂  If this issue doesn't meet the contributing guidelines you can close it, but if so please tell me where to send my request.

**Comment by zachthompson** [comment]
We thought about user submissions early on in developing the product but don't have any plans to implement it atm.

That site has been crawled and hasn't passed our criteria for inclusion

**Comment by PrSunflower** [comment]
@zachthompson  thank you for the reply 🙂

So currently all users can only rely on DDG to maintain the list?

**Comment by J0WI** [comment]
> That site has been crawled and hasn't passed our criteria for inclusion

Could you please publish the criteria? It's not clear whether there is an issue in the criteria, crawler or website and what's required to fix it. I guess the site would pass the criteria for inclusion in HTTPS Everywhere (disclaimer: I'm a ruleset maintainer there).

**Comment by Freso** [comment]
http://help.idlechampions.com/ is another site that works fine with https:// but is not included in the DDG SE list. Given that HTTPS Everywhere is no longer accepting manual additions, this means that there will be a number of sites left out as they may not get crawled by DDG and/or not meet whatever inclusion criteria DDG SE has and there is currently no way to make sure that users visiting those sites from any source using the DDG SE list won’t have the protection granted.

This would seem fine if DDG SE was solely intended to be used by DDG itself, but getting others to use it as a basis as well (such as Pinterest and EFF/HTTPS Everywhere) means that the list has a wider purpose than this. If you intentionally do not wish to protect users on all applicable sites, that should probably be declared more visibly so that the HTTPS Everywhere and other downstream users know that they have to rely on other sources as well.

**Comment by PrSunflower** [comment]
@J0WI thank you for your comment.

Maybe [that](https://spreadprivacy.com/duckduckgo-smarter-encryption/) can help, column "**_How do you check if a site is OK to include in the list?_**" ?
